# Site settings
author: Sue Mir
title: Data Science
header-img: img/home-bg.png
email: susanna.syassen@hotmail.com
copyright_name: Sue Mir
description: > # this means to ignore newlines until "baseurl:"
  Under construction
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Sue-Mir

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
